### ISSUE TITLE
Mapping is missing NativeArray causing older ember versions to not work with some newer addon versions

### ISSUE THREAD

**Issue by runspired** [ember-cli/ember-rfc176-data#488]
should be available from @ember/array 

https://discord.com/channels/480462759797063690/1078725868500832378/1079878481334251590

Example Error

```
Build Error (broccoli-persistent-filter:Babel > [Babel: @ember-data/model]) in -private/promise-many-array.ts

/Users/chasegiunta/repos/dochub/frontend/-private/promise-many-array.ts: @ember/array does not have a NativeArray export
> 1 | import ArrayMixin, { NativeArray } from '@ember/array';
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  2 | import type ArrayProxy from '@ember/array/proxy';
  3 | import { assert, deprecate } from '@ember/debug';
  4 | import { dependentKeyCompat } from '@ember/object/compat';SyntaxError: /Users/chasegiunta/repos/dochub/frontend/-private/promise-many-array.ts: @ember/array does not have a NativeArray export
> 1 | import ArrayMixin, { NativeArray } from '@ember/array';
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  2 | import type ArrayProxy from '@ember/array/proxy';
  3 | import { assert, deprecate } from '@ember/debug';
  4 | import { dependentKeyCompat } from '@ember/object/compat';
    at File.buildCodeFrameError (/Users/chasegiunta/repos/dochub/frontend/node_modules/.pnpm/@babel+core@7.21.0/node_modules/@babel/core/lib/transformation/file/file.js:205:12)
    at NodePath.buildCodeFrameError (/Users/chasegiunta/repos/dochub/frontend/node_modules/.pnpm/@babel+traverse@7.21.2/node_modules/@babel/traverse/lib/path/index.js:105:21)
    at /Users/chasegiunta/repos/dochub/frontend/node_modules/.pnpm/babel-plugin-ember-modules-api-polyfill@3.5.0/node_modules/babel-plugin-ember-modules-api-polyfill/src/index.js:228:20
    at Array.forEach (<anonymous>)
    at processImportDeclaration (/Users/chasegiunta/repos/dochub/frontend/node_modules/.pnpm/babel-plugin-ember-modules-api-polyfill@3.5.0/node_modules/babel-plugin-ember-modules-api-polyfill/src/index.js:188:16)
    at PluginPass.ImportDeclaration (/Users/chasegiunta/repos/dochub/frontend/node_modules/.pnpm/babel-plugin-ember-modules-api-polyfill@3.5.0/node_modules/babel-plugin-ember-modules-api-polyfill/src/index.js:321:9)
    at newFn (/Users/chasegiunta/repos/dochub/frontend/node_modules/.pnpm/@babel+traverse@7.21.2/node_modules/@babel/traverse/lib/visitors.js:149:21)
    at NodePath._call (/Users/chasegiunta/repos/dochub/frontend/node_modules/.pnpm/@babel+traverse@7.21.2/node_modules/@babel/traverse/lib/path/context.js:45:20)
    at NodePath.call (/Users/chasegiunta/repos/dochub/frontend/node_modules/.pnpm/@babel+traverse@7.21.2/node_modules/@babel/traverse/lib/path/context.js:35:17)
    at NodePath.visit (/Users/chasegiunta/repos/dochub/frontend/node_modules/.pnpm/@babel+traverse@7.21.2/node_modules/@babel/traverse/lib/path/context.js:80:31)
```

**Comment by runspired** [comment]
related https://github.com/ember-cli/ember-rfc176-data/issues/12
